apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mw7byietj-nodejs-gitops
  description: This is GitOps manifest for mw7byietj-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=mw7byietj-nodejs
    backstage.io/kubernetes-id: mw7byietj-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: mw7byietj-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mw7byietj-nodejs
